export default {
  home: '/',
  services: '/#services',
  portfolio: '/#portfolio',
  about: '/#about',
  founders: '/#founders',
  faq: '/#faq',
  contact: '/contact/',
  webDesign: '/services/web-design/',
  webDevelopment: '/services/web-development/',
  caseStudies: '/#portfolio',
  blog: '/blog/',
  instagram: 'https://www.instagram.com/ksvisuals.design',
  krishBodaraLinkedin: 'https://www.linkedin.com/in/krishbodara',
  krishSutariyaLinkedin: 'https://www.linkedin.com/in/krish-sutariya-a934573a0',
  email: 'mailto:ksvisualsagency@gmail.com',
  emailText: 'ksvisualsagency@gmail.com',
  phone1: '+91 8488080517',
  phone2: '+91 7861926992',
  phone1Tel: 'tel:+918488080517',
  phone2Tel: 'tel:+917861926992',
  location: 'Surat, Gujarat, India',
  getStarted: '/contact/',
  getInTouch: '/contact/',
};

